changed hw1
ritagord/mipt_python_bm_2021 pull request #2
Opened 2021-09-14 11:58 UTC by ritagord

2021-09-14 19:38 UTC, Alvant commented on hw1_2.py
> +
Ок. По-моему, тут пустая строчка лишняя. Лучше бы имхо `string = input()` было отделить. Ещё можно бы было на отдельной строке провести операцию `alphabet[num]`, типа
```python
num = int(string)
word = alphabet[num]
words.append(word )
```
Такт, если бы поступил какой-то непонятный символ со входа, было бы предельно ясно, в какой строке возникла ошибка (при попытке достать из словаря слово по `num`).

2021-09-14 19:44 UTC, Alvant commented on try_2.sh
> +#!/bin/bash
@ritagord ок, но я это потом посмотрю 😅 Потому что это уже второе задание, и оно должно бы было быть в отдельном реквесте (то есть *только* в отдельном реквесте). Возможно, вы не от той ветки отпочковались, когда начали второе задание делать? Надо было от main, а у вас от feature/homework1?

2021-09-15 04:49 UTC, ritagord commented on try_2.sh
> +#!/bin/bash
Да, извиняюсь, запуталась и не в ту ветку добавила файл, а в нужную Вас не добавила
Сейчас задачка есть в Homework2

2021-09-17 13:41 UTC, Alvant commented on try_2.sh
> +#!/bin/bash
@ritagord да, ок. Файл есть, просто он должен бы был быть *только* в Homework2, а он и тут, и там

(как у вас Vs. как надо было бы)
<img width="960" alt="Снимок экрана (6982)" src="https://user-images.githubusercontent.com/15067981/133792153-2a21d0a7-d267-42c7-86ec-fad613e5016d.png">

<img width="960" alt="Снимок экрана (6983)" src="https://user-images.githubusercontent.com/15067981/133792179-5947afe7-8db1-40be-a504-003fa3488aca.png">

2021-09-17 13:45 UTC, ritagord commented on try_2.sh
> +#!/bin/bash
Спасибо, я кажется поняла свою ошибку, в следующий раз получается надо убедиться git status, что я в main, чтобы ничего лишнего не было?

2021-09-17 14:00 UTC, Alvant commented on try_2.sh
> +echo "home directory:" | tee -a  info.txt
У вас, получается, каждый "кусочек" информации будет на новой строке в файле? Можно бы было печатать "поясняющее сообщение" + "собственно информацию" на одной строке, если использовать echo с параметром `-n` (echo по умолчанию добавляет \n в конец):
```bash
echo -n "home directory:" | tee -a  info.txt
pwd | tee -a  info.txt
```

2021-09-17 14:09 UTC, Alvant commented on try_2.sh
> +ls -R | wc -l | tee -a info.txt
`ls -R | wc -l` Но ведь... так будет "не совсем точно"?) `ls -R` выплюнет информацию в таком виде:
```bash
.:
mipt_python_bm_2021/

./mipt_python_bm_2021:
hw1.py  hw5.py  LICENSE  README.md
```
то есть папка + двоеточие + потом блок с файлами в папке (причём файлы могут быть расположены в 2 и более столбцов). Получается, какие-то строки при подсчёте `wc -l` будут лишними, а в каких-то, наоборот, будет несколько файлов?

2021-09-17 14:11 UTC, Alvant commented on try_2.sh
> +ls -l  |grep "^d"| wc -l | tee -a  info.txt
С пробелами немного схалтурено) `ls -l  |grep "^d"| wc -l` вместо `ls -l  | grep "^d" | wc -l`

2021-09-17 14:14 UTC, Alvant commented on try_2.sh
> +ls -l  |grep "^d"| wc -l | tee -a  info.txt
Ок, но так вы не увидите скрытый папки...
```bash
folder
.secret_folder
```

2021-09-17 14:14 UTC, Alvant commented on try_2.sh
> +
Лишние пустые строчки в конце файла

2021-09-17 14:17 UTC, Alvant commented on try_2.sh
> +echo "files(recursive):" | tee -a  info.txt
Кстати, раз вы создали уже info.txt в домашней папке, то при подсчёте файлов вы и сам info.txt тоже учтёте. По-хорошему, не надо было бы. Но ок)

2021-09-17 14:17 UTC, Alvant commented on try_2.sh
> +echo "folders(non recursive):" | tee -a info.txt
Тут тоже пробел бы не помешал) `folders (non recursive):`

2021-09-17 14:20 UTC, Alvant commented on try_2.sh
> +#!/bin/bash
Кстати, имя файла, кажется, не очень удачное: `try`?)

2021-09-17 14:23 UTC, Alvant commented on try_2.sh
> +echo "username:" $USER | tee -a info.txt
Формат записи информации о дате (в две строки ведь?) отличается от формата тут (в одну строку)

2021-09-17 14:24 UTC, Alvant commented on try_2.sh
> +echo "username:" $USER | tee -a info.txt
`$USER`: Ок. Можно бы было ещё `whoami` использовать, например

2021-09-17 14:24 UTC, Alvant commented on try_2.sh
> +echo "os:" $OSTYPE | tee -a info.txt
`$OSTYPE`: Ок. Ещё можно бы было попробовать `uname`

2021-09-17 14:26 UTC, Alvant requested changes
@ritagord ок! Но в скрипте стоит поправить пару моментов:
* подсчёт файлов: кажется, сейчас выход `lr -R` не позволяет вам "просто взять и посчитать строки" для нахождения числа файлов
* подсчёт папок: "секретные" надо бы тоже учесть

2021-09-17 15:57 UTC, Alvant commented on try_2.sh
> +#!/bin/bash
Да, да. Новые ветки (как правило) лучше начинать от main. Иначе если начать ветку, например, feature2 от feature1, то все изменения из feature1 перейдут и в feature2. А при создании реквеста из feature_n в main показываются изменения feature_n _по сравнению с main_.

2021-09-29 10:36 UTC, Alvant approved these changes

2021-09-29 10:37 UTC, merged