Homework2
ritagord/mipt_python_bm_2021 pull request #3
Opened 2021-09-14 18:35 UTC by ritagord

Второе задание, основная задача

2021-09-17 14:19 UTC, Alvant requested changes
Оставил комменты по скрипту в ПР https://github.com/ritagord/mipt_python_bm_2021/pull/2

2021-09-19 19:15 UTC, ritagord commented
2 задачка и исправление подсчета скрытых папок в первой

2021-09-23 08:07 UTC, Alvant commented on helper.sh
> +find -name "*.py"
А если у вас есть папка `folder.py`?) Скрипт её ведь тоже выведет? Но надо пути именно до файлов показать

2021-09-23 08:13 UTC, Alvant commented on try_2.sh
> +ls -R | wc -l | tee -a info.txt
Но ведь эту команду тоже исправить стоило бы?) Если я правильно понимаю, то в выводе `ls -R` будет, с одной стороны, много "лишних" строчек. С другой, часть папок будут на одной строчке.

https://github.com/ritagord/mipt_python_bm_2021/pull/2/files#r711089854

2021-09-23 08:14 UTC, Alvant approved these changes

2021-09-29 10:38 UTC, merged