hw7.py
ritagord/mipt_python_bm_2021 pull request #8
Opened 2021-10-23 14:09 UTC by ritagord

Задача про ДНК
Только не уверена, что правильно поняла, в чем суть проверки ДНК на равенство

2021-11-02 21:57 UTC, Alvant commented on hw7..py
> +class polynucleotide_chain(ABC):
Naming для класса не в кассу. Надо бы `PolynucleotideChain`

2021-11-02 21:59 UTC, Alvant commented on hw7..py
> +    def complementary_chain(self):
В базовый? Ок... Хотя в задании вроде говорили только про то, что РНК должна уметь возвращать комплементарную ДНК. ДНК тоже может что-то комплементарное вернуть? 😅 Ну ок)

2021-11-02 21:59 UTC, Alvant commented on hw7..py
> +#!/usr/bin/env python3
Кстати, лишняя точка, видимо, в имени файла

2021-11-02 22:00 UTC, Alvant commented on hw7..py
> +    def printing(self):
Имя как будто немного странное (если я правильно понял, что этот метод делает)

2021-11-02 22:02 UTC, Alvant commented on hw7..py
> +        pass
Не, не, не надо `pass` оставлять. `pass` — это значит можно втихую проскочить и ничего плохого не заметить. Надо делать `raise NotImplementedError()`, чтоб всё "грохнулось", если где-то что-то не то.

2021-11-02 22:02 UTC, Alvant commented on hw7..py
> +    def index(self):
Тоже имя как будто не то. Почитаю дальше, и вернусь сюда)

2021-11-02 22:03 UTC, Alvant commented on hw7..py
> +        if set(first_chain).issubset({"A", "T", "G", "C"}):
`{"A", "T", "G", "C"}` — стоило бы в константу это положить, потому что важно, а сейчас это как бы "между строк"

2021-11-02 22:05 UTC, Alvant commented on hw7..py
> +        complementary = {"A": "T", "T": "A", "G": "C", "C": "G"}
Это отображение тоже "тесно связано" с классом, и по смыслу очень важно. По-моему, это можно бы было сделать классовой константой, например:
```python
class DNA(polynucleotide_chain):
    COMPLEMENTARY = {"A": "T", "T": "A", "G": "C", "C": "G"}

    ...

    def complementary_chain(self):
        ...
        self.COMPLEMENTARY[i]
```

2021-11-02 22:07 UTC, Alvant commented on hw7..py
> +    def complementary_chain(self):
Ок, прочитал реализацию у ДНК. То есть вы в этом методе хотите просто цепочку вернуть, как строку? Ок. Стоило бы тогда тип хотя бы указать, уже бы вопросов меньше было бы:
```python
def complementary_chain(self) -> str:
```

2021-11-02 22:10 UTC, Alvant commented on hw7..py
> +        s_chain = ''.join(second_chain)
Ну, вместо новой переменной с дурацким именем можно бы было просто сделать:
```python
return ''.join(second_chain)
```
А вообще, имя `second_chain`, получается, не очень удачное. Потому что `first_chain` — это строка, а `second_chain` (которая, ожидаешь, будет по смыслу похожа на `first_chain`) оказывается массивом.

P.S. В Питоне со строками можно работать так же удобно, как с массивами (потому что строки — "массив символов")

2021-11-02 22:11 UTC, Alvant commented on hw7..py
> +            raise Exception
При выкидывании исключения хорошо бы всегда сообщение ещё оставлять информативное:
```python
raise Exception("...")
```

2021-11-02 22:12 UTC, Alvant commented on hw7..py
> +    def index(self, i = int):
`i = int` — это, видимо, опечатка? 😅 Вы имели в виду:
```python
def index(self, i: int):
```

2021-11-02 22:13 UTC, Alvant commented on hw7..py
> +    def index(self, i = int):
В базовом классе выше сигнатура у метода другая: `def index(self):` Поэтому формально вы не тот метод переопределили, что в базовом объявлен как абстрактный. Видимо, надо в базовом поправить.

2021-11-02 22:16 UTC, Alvant commented on hw7..py
> +        return print(self.first_chain[i], second_chain[i])
`return print(...)` 🤯 💥
1. Print ничего не возвращает, поэтому из `return` ничего не улетит
2. Лучше в этом методе вообще ничего не выводить. Иначе с ним сложнее будет работать. Пусть только отдаёт информацию через return. А дальше её уже можно вывести на экран, сохранить в файл и т.д.

2021-11-02 22:21 UTC, Alvant commented on hw7..py
> +        return print(f_chain, s_chain)
Ну, помимо того, что опять `return print` 🙃, тут ещё и... логика "сломана". Метод `__add__` — это сложение. Вы складываете две ДНК и ожидаете получить... новую ДНК? Кажется, разумно. Раз сказано, что для ДНК определено сложение, это значит, что каждой паре ДНК ставится в соответствие новая, которая строится из двух по определённому правилу. Поэтому из метода `__add__` должна улететь не строка, не кортеж из двух строк, а *новый объект класса ДНК*, у которого строчки "склеены"

2021-11-02 22:22 UTC, Alvant commented on hw7..py
> +        fst_chain = []
`first_chain`

2021-11-02 22:25 UTC, Alvant commented on hw7..py
> +        for i in range(len(shorter_chain)+1, len(longer_chain)):
Точно надо +1 делать для левой границы?.. Кажется, нет, ведь в `range(len(shorter_chain))` граница не включается?

2021-11-02 22:25 UTC, Alvant commented on hw7..py
> +        f_chain = DNA(frst_chain)
Вот если бы было
```python
return DNA(frst_chain)
```
то было бы что надо)

2021-11-02 22:27 UTC, Alvant commented on hw7..py
> +        # днк1 = днк2 вне зависимости от порядка цепочек?
? Ааа... Хм... Ну, видимо, как вы решите) Хорошее наблюдение, что на самом деле есть "несколько вариантов". И да, согласен: кажется, самый естественный — это не учитывать порядок цепочек.

2021-11-02 22:29 UTC, Alvant commented on hw7..py
> +        if self.first_chain == other.first_chain or second_chain == other.first_chain:
Вот если бы было
```python
return self.first_chain == other.first_chain or second_chain == other.first_chain
```
то было бы что надо)

Метод `__eq__` — он булевский. Должен отдавать True, если равны. И False, если не равны.

2021-11-02 22:31 UTC, Alvant commented on hw7..py
> +    def index(self):
Кажется, что тут должен бы был быть `__getitem__`. Раз просят поддержать обращение по индексу с нуклеиновой кислоте, это значит, что должна работать штука `rna[i]` — как у массива или у строки. А за это отвечает отдельный magic метод.

2021-11-02 22:34 UTC, Alvant commented on hw7..py
> +    def printing(self):
В общем, кажется, бОльший смысл имело бы определение метода `__str__`: не надо делать `print`. Кому надо, занесёт эту информацию куда надо (выведет на экран, отправит по email, ...). Вам же важно именно вернуть информацию в строковом виде. Это — основное. И за это как раз отвечает метод `__str__` (ну, и про `__repr__` можно ещё вспомнить).

2021-11-02 22:35 UTC, Alvant commented on hw7..py
> +        # днк1 = днк2 вне зависимости от порядка цепочек?
👍

2021-11-02 22:35 UTC, Alvant commented on hw7..py
> +class RNA:
Нет наследования? 😅 💦

2021-11-02 22:37 UTC, Alvant commented on hw7..py
> +    def index(self, i = int):
`i = int` — значит, это была не опечатка?) 😅 Или тут сыграл копипаст?)

2021-11-02 22:39 UTC, Alvant commented on hw7..py
> +        longer_chain = max(chains, key = len)
Этот `__mul__` очень похож на предыдущий?.. А как же принцип DRY?) Надо с этим что-то сделать. Видно, что основная часть методов `__mul__` буквально одинакова. Значит... это можно куда-то в одно место положить и оттуда вызывать? Например, в базовый класс?

2021-11-02 22:41 UTC, Alvant commented on hw7..py
> +
А метод `complementary_chain` ещё надо реализовать? Раз он абстрактный в базовом классе

2021-11-02 22:42 UTC, Alvant commented on hw7..py
> +            chain_ch = random.choice(chains)
`chain_ch`? (что такое `_ch`?)

2021-11-02 22:54 UTC, Alvant requested changes
Ок. Но кое-что нужно доработать:
* имя базового класса `polynucleotide_chain` надо поправить
* `pass`-ы из базового надо заменить на `raise NotImplementedError`
* метод `printing` надо заменить на `__str__`
* вместо метода `index` должен бы был быть magic метод `__getitem__`
* `complementary = {"A": "T", "T": "A", "G": "C", "C": "G"}` надо вынести в константу (потому что важная штука и потому что сейчас это даже как бы в двух местах используется: и в конструкторе, и в методе `complementary_chain` — надо бы в одном месте собрать)
* `i = int` надо поправить
* все штуки в духе `return print` надо починить: метод должен возвращать то, что от него ожидают, чтоб он вернул (`__eq__` возвращает бул, `__add__` возвращает результат сложения (новую НК), `__mul__` возвращает результат умножения (тоже новую НК))
* метод `__mul__` сейчас почти дублируется у РНК и у ДНК — надо бы, чтоб без дублирования
* класс RNA должен наследоваться от базового
* видимо, в RNA надо ещё реализовать `complementary_chain`, раз этот метод есть у базового?

2021-11-27 18:03 UTC, ritagord commented
Постаралась исправить все замечания, извините что так поздно

2021-11-27 20:29 UTC, Alvant commented on hw7_nov.py
> +Created on Sat Oct 23 11:36:20 2021
Зачем вам коммент о времени создания, такой же, как в первом файле?) Кстати, можно (лучше) было не делать новый файл, достаточно было внести правки в первый.

2021-11-27 20:30 UTC, Alvant commented on hw7_nov.py
> +    @abstractmethod
Ок, можно использовать такой декоратор (но вообще не обязательно). Только тогда не очень понятно, почему вы его только на `__str__` навесили.

2021-11-27 20:30 UTC, Alvant commented on hw7_nov.py
> +    def __getitem__(self):
У `__getitem__` сигнатура должна быть `__getitem__(self, index: int)`

2021-11-27 20:31 UTC, ritagord commented on hw7_nov.py
> +Created on Sat Oct 23 11:36:20 2021
Это я как раз прошлый редактировала, просто это забыла поменять(

2021-11-27 20:32 UTC, Alvant commented on hw7_nov.py
> +        fst_chain = []
`fst`, `frst` 😐

2021-11-27 20:37 UTC, Alvant commented on hw7_nov.py
> +    def __mul__(self, other):
Не очень правильно было называть этот метод `__mul__`, потому что это всё-таки не умножение "базовых нуклеиновых кислот", ведь улетает из него не кислота, а строка. Ну, то есть да, логику по умножению можно было оставить в базовом классе, но метод надо бы было этот по-другому назвать. А `__mul__` уже надо бы было определить именно в классах ДНК и РНК.

2021-11-28 14:54 UTC, Alvant commented on hw7_nov.py
> +Created on Sat Oct 23 11:36:20 2021
Ну ок)

P.S.
А вообще, с комментами да, их тоже надо не забывать поддерживать актуальными, потому что это тоже "часть кода" :nerd_face:

2021-11-28 15:05 UTC, Alvant commented on hw7_nov.py
> +        for i in range(len(shorter_chain)+1, len(longer_chain)):
Так вы всё-таки думаете, тут нужен +1?)

2021-11-28 15:05 UTC, Alvant commented on hw7_nov.py
> +        frst_chain = ''.join(fst_chain)
Вместо придумывания нового старого имени можно бы было сделать просто
```python
return ''.join(fst_chain)
```

2021-11-28 15:08 UTC, Alvant commented on hw7_nov.py
> +    global complementary_DNA
? Нет, не надо никаких `global`:
```python
class DNA(PolynucleotideChain):
    COMPLEMENTARY_DNA = {"A": "T", "T": "A", "G": "C", "C": "G"}

    ...

    def some_method(self):
        ... self.COMPLEMENTARY_DNA ...

if __name__ == '__main__':
    ...
    
    print(DNA.COMPLEMENTARY_DNA)
```

2021-11-28 15:46 UTC, Alvant commented on hw7_nov.py
> +    global complementary_DNA
То есть не нужен `global`, потому что словарь лежит внутри класса: переменной можно пользоваться, но через класс (или через объект класса).

2021-11-28 15:47 UTC, Alvant commented on hw7_nov.py
> +            raise Exception
Тут можно бы было `ValueError` бросить

2021-11-28 15:47 UTC, Alvant commented on hw7_nov.py
> +            second_chain.append(complementary_DNA[i])
`self.complementary_DNA` (к тому, что `global` не нужен)

2021-11-28 15:49 UTC, Alvant commented on hw7_nov.py
> +        s_chain = ''.join(second_chain)
Ну, чтоб было в едином стиле, надо было именовать `snd_chain` и `scnd_chain` )

2021-11-28 15:49 UTC, Alvant commented on hw7_nov.py
> +    def __getitem__(self, i = int):
`i = int` :neutral_face:

2021-11-28 15:51 UTC, Alvant commented on hw7_nov.py
> +        return f_chain, s_chain
Нет: сложение ДНК должно давать снова ДНК (а не тьюпл из двух строк)

2021-11-28 15:52 UTC, Alvant commented on hw7_nov.py
> +        return frst_chain, s_chain
Тоже: умножение ДНК должно возвращать ДНК. Операция умножения: пара ДНК -> новая ДНК
```python
return DNA(frst_chain)
```

2021-11-28 15:53 UTC, Alvant commented on hw7_nov.py
> +        if self.first_chain == other.first_chain or second_chain == other.first_chain:
```python
return (
    self.first_chain == other.first_chain
    or second_chain == other.first_chain
)
```

2021-11-28 15:54 UTC, Alvant commented on hw7_nov.py
> +        return print(self.first_chain)
`return print` 😔

2021-11-28 15:57 UTC, Alvant commented on hw7_nov.py
> +        chains = [self.first_chain, other.first_chain]
Кстати, вы тут достаёте `first_chain` из `self`. Но конструктора у базовой нуклеиновой кислоты, где бы в `self` была положена `first_chain`, нет. То есть по-хорошему надо бы было добавить конструктор в `PolynucleotideChain`: `__init__(self, first_chain)`. Но тогда во всех дочерних классах надо бы было в конструкторах использовать `super().__init__(first_chain)` (чтоб "по-грамотному" отнаследовать)

2021-11-28 16:06 UTC, Alvant commented on hw7_nov.py
> +            return True
`else`?) :sweat_smile: "Ничего"?)

2021-11-28 16:07 UTC, Alvant commented on hw7_nov.py
> +        return fst_chain, s_chain
```python
return DNA(fst_chain)
```

2021-11-28 16:27 UTC, Alvant approved these changes
Ок! Но есть пара моментов:
* хорошо бы добавить конструктор в `PolynucleotideChain`
* метод `__eq__` у ДНК и РНК сейчас возвращает либо `True`, либо "ничего"
* надо убрать `global` в определении нуклеотидов
* методы `__add__` и `__mul__` должны возвращать не строку (и не тьюпл строк), а нуклеиновую кислоту: две НК -> новая НК
* ну, а строчки `i = int` и `return print` always make me cry 🌢

2021-11-28 16:42 UTC, ritagord commented
so sorry about return print (╯•﹏•╰)

2021-12-10 14:44 UTC, merged